POST http://127.0.0.1:8001/login/
Content-Type: application/json

{
  "email": "superuser123@gmail.com",
  "password": "superuser"
}

### 

###
POST http://127.0.0.1:8001/login/
Content-Type: application/json

{
  "email": "test@123.com",
  "password": "12345678"
}


###
POST http://127.0.0.1:8001/api/token/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3Njc5NDcxOSwiaWF0IjoxNzc2NzA4MzE5LCJqdGkiOiJlOTRkMTlmNzVkMTc0OGY5YWQ4N2Y4YTMzMGY5ZDViMiIsInVzZXJfaWQiOiIzIn0.K06v-oEyRKsg4CUVB7cS4rQqd7LlGifPBeJHYVvjF6g


# Refresh ::  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3Njc5NDcxOSwiaWF0IjoxNzc2NzA4MzE5LCJqdGkiOiJlOTRkMTlmNzVkMTc0OGY5YWQ4N2Y4YTMzMGY5ZDViMiIsInVzZXJfaWQiOiIzIn0.K06v-oEyRKsg4CUVB7cS4rQqd7LlGifPBeJHYVvjF6g

###
POST http://127.0.0.1:8001/create-user/
Content-Type: application/json

{
  "username": "testuser",
  "email": "test2@123.com",
  "password": "12345678"
}



###
GET http://127.0.0.1:8001/teams/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2NzA5NzI4LCJpYXQiOjE3NzY3MDk0MjgsImp0aSI6ImEyZDZlZGY4M2ZkNzRmOThhMmFmMzkxMWY1ZDczODAzIiwidXNlcl9pZCI6IjMifQ.vTykYSUhr_pZDc2F4vnr6rXkG1vmZUlzHyaRnH0edaE

###
GET http://127.0.0.1:8001/students/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2NzA4NjE5LCJpYXQiOjE3NzY3MDgzMTksImp0aSI6ImE5NTM2MWY3ZWIzNDRmOGE5YmU1ZGFiNWZiNzJkZTM3IiwidXNlcl9pZCI6IjMifQ.WK_tD17yKiLxa9cY1uuMsp2GoESQMt3N4BbR5SdMRuA

###
DELETE http://127.0.0.1:8001/students/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2NzA4NjE5LCJpYXQiOjE3NzY3MDgzMTksImp0aSI6ImE5NTM2MWY3ZWIzNDRmOGE5YmU1ZGFiNWZiNzJkZTM3IiwidXNlcl9pZCI6IjMifQ.WK_tD17yKiLxa9cY1uuMsp2GoESQMt3N4BbR5SdMRuA


###
POST  http://127.0.0.1:8001/students/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2NzA5NzI4LCJpYXQiOjE3NzY3MDk0MjgsImp0aSI6ImEyZDZlZGY4M2ZkNzRmOThhMmFmMzkxMWY1ZDczODAzIiwidXNlcl9pZCI6IjMifQ.vTykYSUhr_pZDc2F4vnr6rXkG1vmZUlzHyaRnH0edaE
Content-Type: application/json

{
  "enrollment_no": 1,
  "name": "John Doe",
  "email": "john.doe@example.com",
  "age": 25,
  "team": "ab3e7500-7b5b-4add-8acc-01bed6624d89"
}

###
POST  http://127.0.0.1:8001/team/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2NzA5NzI4LCJpYXQiOjE3NzY3MDk0MjgsImp0aSI6ImEyZDZlZGY4M2ZkNzRmOThhMmFmMzkxMWY1ZDczODAzIiwidXNlcl9pZCI6IjMifQ.vTykYSUhr_pZDc2F4vnr6rXkG1vmZUlzHyaRnH0edaE
Content-Type: application/json

{
  "team_name": "Team A",
}